apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp
spec:
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
      - name: todoapp
        image: foxinious/django-todo-fox:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: todoappsvc
spec:
  type: LoadBalancer
  selector:
    app: todoapp
  ports:
  - port: 80
    targetPort: 8000
---
# ingress host based
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todoapp-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: "todoapp.rahulrajsingh.in"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: todoappsvc #service name where triffic to be redirected, traffic will be comming from loadbalancer. 
            port:
              number: 80 # servie port on which app's service which is handling that appliation. 

